name: add_to_cart_animation
description: A flutter plugin which provide you add to cart animation as in the gif.
version: 0.0.7
author: Ömer Bayrak <omerbyrk8@gmail.com>
homepage: https://github.com/omerbyrk/add_to_cart_animation
publish_to: https://pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter: 